### ISSUE TITLE
Feature Request: resize/move using percentages

### ISSUE THREAD

**Issue by toupeira** [skx/kpie#24]
First, thanks for creating this project! :sparkling_heart: 

I recently switched to a multihead setup with differing resolutions, and realized that my devilspie configuration doesn't really support that with its fixed pixel sizes. After looking for alternatives I found kpie and noticed it has the same limitation.

It would be great if you could add support for percentages in the `xy` and `size` functions, or alternatively add `display_width` / `display_height` functions to get the resolution of the current display ("current" = where the mouse cursor is?). I did try the `screen_*` functions but they return the resolution of the full X11 screen (i.e. the combined size of all displays).

For reference, my main use case is "tiling" certain windows to the left or right side, i.e. resize them to half width and maximize them vertically.

**Comment by skx** [comment]
Thanks for the pleasant feedback.

Currently we perform all our operations via the excellent `libwnck` library.  At the moment the code for `screen_width()`, for example, looks like this:

        int lua_screen_width(lua_State * L)
        {
            WnckScreen *screen = wnck_window_get_screen(g_window);
            lua_pushinteger(L, wnck_screen_get_width(screen));
            return 1;
        }

What that does is get the "screen" associated with the `g_window` (i.e. current window) and return the dimensions of that screen.   I had assumed the screen would work appropriately for multi-monitor setups, but I'm unable to test.  The alternative is to measure the size of the _workspace_, I'm not sure if that will do what you want, but I hope it would be easy to test.

If you could update your source, editing `bindings.c` to read as follows then I _suspect_ you'd find that the `screen_width()` function would return a value describing the current desktop:

        int lua_screen_width(lua_State * L) {
              WnckScreen *screen = wnck_window_get_screen(g_window);
               WnckWorkspace *work = wnck_screen_get_active_workspace (screen);
               int width = 0;

               if ( work != NULL )
                   width = wnck_workspace_get_width (work);

               lua_pushinteger(L, width);
               return 1;
          }

If that works: great, and I'll update to make a similar change for the height.  If it doesn't work I'll have to try something more complex.  We do use `X11` directly for a couple of operations, but I'm hazy on how multi-monitor stuff works at the xlib-level.

**Comment by toupeira** [comment]
@skx and thanks for the quick reply!

It's been ages since I've done anything with C, so I thought I'd quickly take a look with the `python-wnck` bindings. This is using `libwnck22` on Debian, same as the `kpie` package.

My screen resolutions are:
- primary 3520x1980
- secondary 3840x2400

Using this code:

```python
#!/usr/bin/env python

import wnck

screen = wnck.screen_get_default()
screen.force_update()
workspace = screen.get_active_workspace()

print("screen:    %dx%d" % (screen.get_width(), screen.get_height()))
print("workspace: %dx%d" % (workspace.get_width(), workspace.get_height()))
```

yields this output:

```
screen:    3840x4380
workspace: 3840x4380
```

Same result with python3 / libwnck-3. 

FWIW `wmctrl`, which apparently uses `libx11` directly, also returns this size for all workspaces:

```
$ wmctrl -d
0  * DG: 3840x4380  VP: 0,0  WA: 0,55 3840x4259  Workspace 1
1  - DG: 3840x4380  VP: N/A  WA: 0,55 3840x4259  Workspace 2
2  - DG: 3840x4380  VP: N/A  WA: 0,55 3840x4259  Workspace 3
```

From what I gather using `libxrandr` would be the correct way to get this information on X11.

On a completely unrelated note: your name sounded familiar, and after finding out you were the guy behind xen-tools I stumbled over this [old Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439874) of mine. Hello again :grin:

**Comment by skx** [comment]
Hello again, what a small world!

Thanks for your experimentation, I'll have to dig around with Xlib/X11/XRandR to see if I can get decent sizes out of them.  I suspect this will either take a while, or be a bit tricky.  If you're willing to test things though that will be a bonus - give that I have only a single monitor setup available to me.

**Comment by skx** [comment]
I've updated the code now, pushing a new branch, and I _think_ this will do what you want:

* `screen_height()` will show the height for the display the given window is positioned upon.
* `screen_width()` will show the width for the display the given window is positioned upon.

That lets you calculate sizes appropriately, much as I do for pidgin in [this example](https://github.com/skx/kpie/blob/master/samples/pidgin.lua).

To test this:

1. Checkout the code, somewhere suitable:

     git clone https://github.com/skx/kpie.git

2. Switch the the new branch:

      cd kpie
      git checkout 24-multi-monitor-aware-width-height

3. Build the binary:

      make

4.  Test it :)

If you let me know how you get on that'll be good, and if it works I'll make a new release soon..

**Comment by toupeira** [comment]
@skx thanks, sorry didn't get around to testing yet!

When my secondary display is connected the `screen_*` functions always return its resolution, no matter if the focused window (or the mouse cursor) is on my primary display or not. Even if I move all windows to the primary display I still get the secondary display's resolution. If I unplug it, I correctly get the primary display's resolution though.

Let me know if you have ideas for other things to test.

**Comment by skx** [comment]
I made a new release with my update; short of that i'm out of ideas.  The best I can suggest is that somebody with a multi-monitor setup, especially with wnck experience, tells me what I'm missing...

**Comment by toupeira** [comment]
@skx finally found some time to hack on this a bit. I think the problem with the code in https://github.com/skx/kpie/pull/25 is that `XRRGetScreenResources` always returns all screens, no matter which window is passed. I couldn't find any other XRandr methods to accomplish this, but found some example scripts at https://superuser.com/questions/603528/how-to-get-the-current-monitor-resolution-or-monitor-name-lvds-vga1-etc to determine the monitor based on the window's geometry.

**Comment by toupeira** [comment]
(sorry, accidentally clicked on "Close and comment" before I was finished...)

@skx finally found some time to hack on this a bit. It looks like the problem with the code in #25 is that `XRRGetScreenResources` always returns all screens, no matter which window is passed. I couldn't find any other XRandr methods to accomplish this, but found some example scripts at https://superuser.com/questions/603528/how-to-get-the-current-monitor-resolution-or-monitor-name-lvds-vga1-etc to determine the monitor based on the window's geometry.

So I ended up putting this into a bash script and calling it from kpie's Lua code, and also had to add the monitor offset to the `xy()` calls since wnck uses the full X11 screen as reference. I also had to add a small 50ms sleep delay to make sure I would get the right monitor, I assume this is some brokenness in gnome-shell.

You can see my full setup at https://github.com/toupeira/dotfiles/commit/943a997eef20c01367fc32f49acca12fbea291f5, it's probably tricky to generalize this to something that will work with more than 2 monitors, or monitors that aren't arranged horizontally, but maybe this will help out somebody else who stumbles over this issue ;-)

**Comment by skx** [comment]
I'm glad you got it working, and I guess it is safe for me to close now :)
